version: "3.7"
services:
  local-db:
    image: mysql:5.7
    command: --lower_case_table_names=1
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
